# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Release beta of app"
lane :beta do
  get_certificates(
    team_id: "B3954BPX4P"
  )
  get_provisioning_profile(
    team_id: "B3954BPX4P",
    app_identifier: "outware.RxDojo",
    adhoc: true
  )
  # increment_build_number
  build_app(
    scheme: "RxDojo",
    include_bitcode: true
  )
  # hockey(
  #   api_token: "9ca0fe4f511d45dbb51b4b8bcf37aabd"
  # )
end